export enum ROLE_SHOP {
  SHOP = 'shop',
  WRITER = 'writer',
  EDITOR = 'editor',
  ADMIN = 'admin',
}

export enum HEADER_KEY {
  LOG_ID = 'x-log-id',
  CLIENT_ID = 'x-client-id',
  AUTHORIZATION = 'authorization',
  REFRESH_TOKEN = 'x-refresh-token',
}

export const ERR_CODE = {
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR'.toLowerCase(),
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS'.toLowerCase(),
  INVALID_SHOP_ID: 'INVALID_SHOP_ID',
};

export const APP_ACTION = {
  HANDLE_EXCEPTION: 'HANDLE_EXCEPTION'.toLowerCase(),
  REGISTER: 'REGISTER'.toLowerCase(),
  LOGIN: 'LOGIN'.toLowerCase(),
  REFRESH_TOKEN: 'REFRESH_TOKEN'.toLowerCase(),
};

export enum ENV_KEY {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',

  MONGO_URI = 'MONGO_URI',

  JWT_EXPIRATION = 'JWT_EXPIRATION',
  JWT_SECRET = 'JWT_SECRET',

  GOOGLE_RECAPTCHA_SECRET = 'GOOGLE_RECAPTCHA_SECRET',
  GOOGLE_RECAPTCHA_VERIFY_ENDPOINT = 'GOOGLE_RECAPTCHA_VERIFY_ENDPOINT',

  SMTP_MAIL_FROM = 'SMTP_MAIL_FROM',
  SMTP_HOST = 'SMTP_HOST',
  SMTP_PORT = 'SMTP_PORT',
  SMTP_SECURE = 'SMTP_SECURE',
  SMTP_USERNAME = 'SMTP_USERNAME',
  SMTP_PASSWORD = 'SMTP_PASSWORD',

  APP_PUBLIC_URL = 'APP_PUBLIC_URL',

  AUDIT_WEBHOOK_URL = 'AUDIT_WEBHOOK_URL',
}

export const INJECTION_TOKEN = {
  AUDIT_SERVICE: Symbol.for('AUDIT_SERVICE'),
  HTTP_SERVICE: Symbol.for('HTTP_SERVICE'),
};
